### ISSUE TITLE
at(index)-lens for tuples 

### ISSUE THREAD

**Issue by merisbahti** [akheron/optics-ts#13]
Heya, consider the case:

```typescript
optic<[number, string]>().index(0) 
```

This produces a Prism, but we know that this is a tuple, and would make more sense for it to produce a lens (since there's no doubt that the item at index 0 for the tuple is a number).

Is there something I've missed here? It's important for me to be able to focus on a tuple and for that optic to be a lens and not a prism.

**Comment by akheron** [comment]
No, you haven’t missed anything. Indexing tuples with a lens definitely needs to be added.

**Comment by akheron** [comment]
Implemented in #14. It uses TypeScript 4.1 features, so we have to wait until its release before merging.

**Comment by merisbahti** [comment]
Thank you, this is appreciated.

**Comment by akheron** [comment]
Fixed in #14
