### ISSUE TITLE
 DataCloneError: Failed to execute 'put' on 'IDBObjectStore': Symbol(__remove_me__) could not be cloned.

### ISSUE THREAD

**Issue by lanyusan** [akheron/optics-ts#219]
I am using your library on a project. So far works great. But when I need to persist data object to a browser db, specifically I use Dexie,
this error showed up.

Is there away to purge out this Symbol easily and fast down an object tree for persistence?

Thanks. I really liked your library and hope to use it in production. Hope to find a solution to this problem.

**Comment by akheron** [comment]
You should never see that symbol, it’s only used internally during the remove operation. It may pop up if you ignore the typescript typings and call remove on something that’s not removable.

**Comment by lanyusan** [comment]
Thanks for the clarification. I would tune my code to see if it goes away.
