### ISSUE TITLE
expose lens constructor?

### ISSUE THREAD

**Issue by valyagolev** [akheron/optics-ts#268]
Stuck wanting a function to construct my own `lens()`. The reason for it is that I'm trying to use `optics-ts` with es Map, because basically I need an object that preserves item ordering. It requires using `.get()` and `.set()` to get/set entries; object syntax doesn't work. Unfortunately I can't figure out how to lens into it.

**Comment by akheron** [comment]
Hi and thanks for bringing this up!

I don't have anything against adding a generic `lens` constructor, but I'm afraid using it with `Map` will not be very useful.

1. You won't be able to generalize over `Map`'s type arguments, so key and value types will be static
2. You would also have operate on a static key
3. optics-ts assumes immutable data, and cloning a `Map` is not pretty

It would look something like this:

```typescript
const lens = O.optic<Map<string, number>>().lens(
   // The lens operates on a static key 'foo', and we must assume that it always exists in the map
  (s) => s.get('foo')!,

  // AFAIK, this is the cleanest way to clone a Map with one key changed
  (s, v) => {
    const result = new Map(s);
    result.set('foo', v);
    return result
  }
)
```

I'll add more comments about the implementation to your pull request :)

**Comment by valyagolev** [comment]
Yup exactly, that's what I just wrote earlier today.

```
o.lens(
          map => map.get(id) as MyType,
          (map, value: MyType) => new Map(map).set(id, value)
        ),
```

(Yeah, it's closing over a particular id)

This is part of a pretty involved system involving `jotai`'s atoms, and while this particular lens is not my favorite one, the astonishing composability of the whole system is just what we need. So I just want to have an escape hatch like this to make sure we can extend the system indefinitely :-)

**Comment by akheron** [comment]
FYI, I added a standalone optics version of `lens` in #272

**Comment by valyagolev** [comment]
thank you, didn't think about this! could we expect a new version sometime in the future?

**Comment by akheron** [comment]
Oh yeah, it’s published already 😊
