### ISSUE TITLE
TS is complaining when using Traversal

### ISSUE THREAD

**Issue by NicoBru31** [akheron/optics-ts#271]
Hello ! 
First I'd like to thank you for this lib, this is amazing how many problems it solves !
But I'm facing an issue with Traversal though:

```javascript
import * as O from 'optics-ts';

type Person = {
    name: string;
    friends: Person[];
};

const friendsNames = O.optic<Person>().prop('friends').elems().prop('name');
```

Whenever I try to use `elems`, TS is throwing an error : `Argument of type '"name"' is not assignable to parameter of type 'keyof NotAnArrayType<Person[]>'.ts(2345)`

I'm using `optics-ts` with TypeScript 4.8.3

**Comment by akheron** [comment]
Works fine for me, see [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wPJwGZQiOAcgjBmAGNUBaGVQgWACgmYBPMAUzgAUOpUIAOzgBeOAG8mcaXEHIQHAFxxUMKMEEBzANxSZuYB0EATVMt78hAbQC6uxgF97TckNU51R0wDl5HdGIYAHQkZOQAPBYCggB8ABQAlEFgeGBxhAZedEkcADYcIKiJyanpcgqECc6MroLu5f6imEGuufnkMHGZJqi+CqgJceKyfsoARNgQEGMANB6GPcq2cA4JTEA).

Which version of optics-ts are you using? Do you have `"strict": true` in tsconfig.json?

**Comment by NicoBru31** [comment]
Oh my bad ! I'm working with lerna and have multiple tsconfig files. The one used by my file had `strict: false` 😵‍💫 
Once again thanks for this amazing lib and your answer !
