### ISSUE TITLE
Maybe a better solution for this types on valueOr and optional?

### ISSUE THREAD

**Issue by wcastand** [akheron/optics-ts#284]
started to use optics for work and i run into an issue with type and i'm not sure if i just use optics badly or not.

i have a record of type `IUser` and i created the optics for it (small sample):

```typescript

export const lInitialPayment = O.compose("initialPayment", O.optional)
export const lInitialPaymentStatus = O.compose(lInitialPayment, O.optional, "status")
```

`initialPayment` can be undefined as well as `initialPayment.status`

ideally i would use `valueOr` to defined a default value

```
export const lInitialPaymentStatus = O.compose(lInitialPayment, "status", valueOr(EInitialPaymentStatus.PROCESSING)
```

but doing that doesn't send the type i was expecting. `EInitialPaymentStatus` but instead sends `EInitialPaymentStatus | undefined` 

i'm guessing it's because `lInitialPayment` has optional and i'd rather not have a mix of `Lens` and `Prism` since it would require using `get` or `preview` which is annoying to expect to know for new dev and also makes it really hard to make helpers function like `exist: (optic, data) => boolean` since i wouldn't know if have to use `get` or `preview` of the optic as far as i know.

To avoid having to think which one to use, everything is a prism. + my user can have all his value undefined pretty much outside of like 3 fields so it makes sense to have everything optional but then `valueOr` should remove the `undefined` from the type from what i understand it does.

Looking at the types i managed to make a `getOr` function that return the right types (the one i expect at least):

```typescript
export function getOr<
	C extends "Prism" | "Traversal" | "AffineFold" | "Fold" = "Prism",
	A extends HKT = any,
	S = any,
	D = any,
>(optic: Optic<C, A, any, any>, data: S, defaultValue: D) {
	return O.preview(O.compose(optic, O.valueOr(defaultValue)), data) as Apply<A, S> extends infer AU
		? AU
		: never
}

``` 

Just wanted to know if i do something really bad with optics to get this result or if it could makes sense to look into adapting the current types to match this behavior :)

**Comment by akheron** [comment]
If you use the `optional` prism multiple times, and want to default to a specific value no matter in which level the `undefined` is, you can just say `O.preview(yourPrism, data) ?? defaultValue`. Or am I missing something?

**Comment by wcastand** [comment]
actually not sure it does what i want because if i have this case, i get `string | undefined ` instead of `string`

```ts
export const lInitialPayment = O.compose("initialPayment", O.optional)
export const lInitialPaymentStatus = O.compose(lInitialPayment, O.compose("status", O.optional))
export const lInitialPaymentStatusWithDefault = O.compose(
	lInitialPayment,
	O.compose("status", O.valueOr(EInitialPaymentStatus.PROCESSING)),
)

// Expected: EInitialPaymentStatus
// Actual: EInitialPaymentStatus | undefined
O.preview(lInitialPaymentStatusWithDefault, user)
```

i tried to remove the optional in the first compose to use `.get` but still getting an error :
```ts
export const lInitialPaymentStatusWithDefault = O.compose(
	O.prop("initialPayment"),
	O.compose("status", O.valueOr(EInitialPaymentStatus.PROCESSING)),
) // output -> NoSuchProperty<"status", IInitialPayment | undefined>

```

the source is `user` of type `IUser`: 

```ts

export interface IInitialPayment {
	status: EInitialPaymentStatus
}

export interface IUser {
	[...]
	initialPayment?: IInitialPayment
}
```

**Comment by akheron** [comment]
So, your data type is basically this:
```ts
type MyStatus = 'pending' | 'paid'

interface MyData {
  initialPayment: { status: MyStatus } | undefined
}
```

Let's go through it step by step.

```ts
O.compose('initialPayment') // Lens with focus { status: MyStatus } | undefined
O.compose('initialPayment', O.optional) // Prism with focus { status: MyStatus }
const final = O.compose('initialPayment', O.optional, 'status') // Prism with focus MyStatus

O.preview(final, myData) // MyStatus | undefined
```

You can just write `O.preview(final, myData) ?? 'pending'` to default to pending status.

If you want to use `O.valueOr` instead, you have to use it at the `{ status: MyStatus } | undefined` level instead of `O.optional`:

```ts
const defaultPaymentStatus: { status: MyStatus } = { status: 'pending' }
const final2 = O.compose('initialPayment', O.valueOr(defaultPaymentStatus), 'status') // Lens with focus MyStatus

O.get(final2, data) // MyStatus
```

Now the optic is a lens, so reading through it always succeeds and you don't need to handle `undefined` in the end.
