### ISSUE TITLE
Error: Unable to resolve

### ISSUE THREAD

**Issue by wcastand** [akheron/optics-ts#285]
My expo/react-native project can't load the module `optics-ts/standalone`

```Unable to resolve "optics-ts/standalone" from "src/utils/lenses/user.ts"```

`optics-ts` seems to work fine just an issue with standalone.

when i import `import * as O from "optics-ts/dist/mjs/standalone"`. vscode can't find the types but i get no error from metro on bundle. but he can't find `internals` so it's still not usable.

The project is in a monorepo in case that's a problem. the typings in vscode are found and i don't get an error on the import, the error is only when metro tries to bundle.

the tsconfig has `"strict": true,`

tsconfig:
```
{
	"extends": "expo/tsconfig.base",
	"compilerOptions": {
		"strict": true,
		"baseUrl": "./",
		"paths": {
			"@gg/assets/*": ["./assets/*"],
			"@gg/*": ["./src/*"],
			"*": ["*", "*.ios", "*.android"]
		}
	},
	"exclude": ["scripts"]
}
```

**Comment by akheron** [comment]
It's a hard problem to publish a package to npm that:
1. supports multiple entrypoints (`optics-ts` / `optics-ts/standalone` in this case)
2. supports both CommonJS modules and ECMAScript modules
3. exposes TypeScript typings

The way it's done in optics-ts is a kludge, so I'm not surprised if it doesn't work with all bundlers and build systems.

I don't have a direct solution to your problem, but if you `npm install optics-ts`, you can look at `node_modules/optics-ts` to see how it's done. You can also try to fiddle with the files there to see if you can get it working somehow.
