### ISSUE TITLE
Setting a Prism should always apply no?

### ISSUE THREAD

**Issue by wcastand** [akheron/optics-ts#287]
I'm not sure how it's suppose to work in Optics/lens land but i would expect that when i set a prop or deep prop, it gets set even when it's not yet defined.

```ts
import * as assert from 'assert'
import * as O from 'optics-ts/standalone'
import { pipe } from 'fp-ts/function'
import { some, none } from 'fp-ts/Option'


interface Company {
  name?: string
  address?: string
}
interface Employee {
  name?: string
  company?: Company
}

const emp: Employee= {
  name:'test',
  company:{
    address:'te'
  }
}

const noCompany:Employee: { name:'test2' }

const lName = O.compose('name', O.optional)
const lCName = O.compose('company', O.optional, 'name', O.optional)

// Would expect to set company.name = 'test23' and not just do nothing
O.set(lCName, 'test23', emp) 
// Would expect to set company.name = 'test23' and not just do nothing
O.set(lCName, 'test23', noCompany) 

```

Is there a method to do this in optics?
I use lenses to make it easy to set/update value deep in an object and create easy to use pre-build lens to access/modify data in complex object but with this behavior i can't really do that without expecting every dev to deeply know the object structure and how optics-ts works with `valueOr` / `optional` / `Prism` / etc

**Comment by akheron** [comment]
You have to think what is in the _focus_ of the optic.

A lens always has a focus; it's guaranteed to be focused on something. Writing through a lens always succeeds.

A prism may or may not have a focus. If it does have a focus, then writing through it succeeds. If it doesn't have a focus, writing through it does nothing.

The `O.optional` prism doesn't have a focus if the value it would point to is `undefined`. This lets you continue the chain of optics without having to care about `undefined`s in the path. On the flipside, it stops working if there's an `undefined` where the `O.optional` points at.

Let's look at your example (I shortened it a bit):

```ts
const emp: Employee = {
  name:'test',
  company:{
    address:'te'
  }
}
O.set(O.compose('company', O.optional, 'name', O.optional), 'test23', emp) 
```

What's in the focus of the prism now? `emp.company.name` is `undefined`, so there's no focus! So this does nothing.

Let's remove the last `O.optional`:

```ts
O.set(O.compose('company', O.optional, 'name'), 'test23', emp) 
```

It's still a prism, but its focus is now `string | undefined`, and it _does have_ a focus as long as `company` exists. So, this time it works as you would expect.

Hope this helps.
