### ISSUE TITLE
A benchmark of optics-ts, partial.lenses, and monocle-ts

### ISSUE THREAD

**Issue by lanyusan** [akheron/optics-ts#3]
Hi, thanks for this awesome library. 

I did some benchmark as the title said. In summary optics-ts performance is the best in general. But its `read` is **behind partial.lens**. Is there room for **further improvement**? 

**Detail**

I need to pick a JS/TS optics library for a project. After some initial research, I narrowed down to three candidates: [partial.lenses](https://github.com/calmm-js/partial.lenses.git), [monocle-ts](https://github.com/gcanti/monocle-ts.git), [optics-ts](https://github.com/akheron/optics-ts.git).

As my project is going to manipulate dataset with certain size, I ran some benchmarks, on four operations I cared the most:

- read by lens
- modify by lens
- read array element by predicate
- modify array element by predicate

**Jest run result**

Edit: 
As the test data's array element's id is unique, I used `find` instead of `elems` to run again. The performance of both read and write was improved.
Here is the new test resut:

**Use `find`**
```
  read
    ✓ optics-ts (4ms)
    ✓ monocle-ts (1ms)
    ✓ partial.lenses (3ms)
  write
    ✓ optics-ts (3ms)
    ✓ monocle-ts (4ms)
    ✓ partial.lenses (16ms)
  prism read array element by predicate
    ✓ optics-ts (36ms)
    ✓ monocle-ts (219ms)
    ✓ partial.lenses (6ms)
  prism modify array element by predicate
    ✓ optics-ts (87ms)
    ✓ monocle-ts (30524ms)
    ✓ partial.lenses (338ms)
```

**Use `elems`**
```
  read
    ✓ optics-ts (4ms)
    ✓ monocle-ts (1ms)
    ✓ partial.lenses (3ms)
  write
    ✓ optics-ts (3ms)
    ✓ monocle-ts (4ms)
    ✓ partial.lenses (13ms)
  prism read array element by predicate
    ✓ optics-ts (70ms)
    ✓ monocle-ts (220ms)
    ✓ partial.lenses (6ms)
  prism modify array element by predicate
    ✓ optics-ts (214ms)
    ✓ monocle-ts (31227ms)
    ✓ partial.lenses (344ms)
```

It seems optics-ts has the best overall performance. I inclined to use it for my project. 

Optics-ts is strong in write while partial.lenses is strong in read. I am not sure if there is still room to improve your read to partial.lenses' level..

Here is the benchmark repository.

[js-optics-benchmark](https://github.com/nodeshapes/js-optics-benchmark)

p.s. just realized you are the maintainer of jansson. Now it is clear I will go with optics-ts.

:)

**Comment by lanyusan** [comment]
p.s. just realized you are the maintainer of jansson. Now it is clear I will go with optics-ts.

:)

**Comment by akheron** [comment]
Interesting benchark! I haven't really played attention to making optics-ts fast, and I'm sure there's room for improvement.

**Comment by lanyusan** [comment]
Thanks for the reply. 

Please do optimize the performance. I have tried more of your code against monocle-ts and partial.lenses and found out yours gave my code much more clarity. 

It would be great if read by lens and prism through predicate can be improved to partial.lenses' level. Optics-ts would then definitely win more support.
