### ISSUE TITLE
Errors with typeeerror (incorrect NotAnArrayType)

### ISSUE THREAD

**Issue by merisbahti** [akheron/optics-ts#5]
Heya,

Thanks for this lib, I love it.

In my repo:
https://github.com/merisbahti/io-ts-experiment/blob/master/extract-errors-with-path.test.ts

I copied one of your tests, (see `describe(’lens/filter’)`)
And I get this error:
```
extract-errors-with-path.test.ts:20:26 - error TS2339: Property 'bar' does not exist on type 'NotAnArrayType<Source[]>'.
20     .filter(item => item.bar !== 'quux')
```

(in my repo, I just run `npx tsc extract-errors-with-path.test.ts`

And I’m not sure why I get it, we even share the exact same ts version.

Do you have any wisdom to share here? thanks

**Comment by akheron** [comment]
Hey, thanks for reporting this!

It seems that optics-ts's type juggling does does not work without the `strictNullChecks` compiler option. Your file compiles fine like this:

```
npx tsc --strict extract-errors-with-path.test.ts
```

I added a requirements section to readme that documents this.

**Comment by merisbahti** [comment]
Oh my bad, thank you very much.
