### ISSUE TITLE
Plates, a.k.a ”Recursive traversals”

### ISSUE THREAD

**Issue by merisbahti** [akheron/optics-ts#6]
Heya,

I could not find this in the documentation, but is there anyway to accomplish recursive traversals?

Here’s the docs for haskells control lens plated, which is prior art.
http://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Plated.html

**Comment by akheron** [comment]
No, not possible currently. Do you have an example of how you would like to use it?

**Comment by merisbahti** [comment]
I actually managed to solve it without it, thanks :)
